import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import Header from "../components/Header";
import Stories from "../components/Stories";
import MiniProfile from "../components/MiniProfile";
import Suggestions from "../components/Suggestions";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Instagram</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <main className=" mt-6 max-w-6xl mx-auto flex justify-between px-8 gap-8">
        <section className="flex-1  overflow-x-scroll scrollbar-hide max-w-2xl ">
          <Stories />
          {/* <Posts /> */}
        </section>

        <section className="hidden lg:inline-flex  rounded-md shadow-md py-3 w-[300px]">
          <div className="">
            <MiniProfile />

            <Suggestions />
          </div>
        </section>
      </main>
    </>
  );
}
