import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import Header from "../components/Header";
import Stories from "../components/Stories";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Instagram</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <main className="grid grid-cols-1 md:grid-cols-2 md:max-w-3xl xl:grid-cols-3 xl:max-w-6xl mx-auto">
        <section className="col-span-2 ">
          <Stories />
          {/* <Posts /> */}
        </section>

        <section className="hidden xl:inline-grid md:col-span-1">
          <div className="fixed top-20">
            {/* <MiniProfile /> */}
            {/* <Suggestions /> */}
          </div>
        </section>
      </main>
    </>
  );
}
